### PR TITLE
adjust scaling, add y-axis labels, add margin

### PR DESCRIPTION
**Pull request by darrenmason**
image

### CODE REVIEW

**Comment by philschatz** [comment]
Thanks! Can you merge in changes from master?

**Comment by philschatz** [comment]
I wonder if this should select the right-most unit first; that way students know they can click the numbers and have a way to click "Practice" instead of discovering the circle button or the unit button. @Fredasaurus ?

**Comment by darrenmason** [comment]
I can add first selected unit by default;  also I can use flag label and cloud images from comp and convert to svg;  or if you have svg for them @Fredasaurus ?

**Comment by nathanstitt** [comment]
SVG would be much preferred since it's vector and will scale with the chart without getting a bad case of the jaggies :) 

It may make more sense to draw the Y axis flag labels in the code rather than loading remotely in order to keep the network requests to a minimum and display it faster.  Not sure about that; I'll also bloat the code a bit.

**Comment by Fredasaurus** [comment]
I’ll be working on new vector art early next week. Would delivery mid-Tuesday work.

BTW - I was hoping for animated clouds :)

Fred

**Comment by darrenmason** [comment]
sure, I can animate them; was thinking prioritize the functional/layout bits first

**Pull request merged**
