### PR TITLE
Selenium: clean up helper commands

### PR DESCRIPTION
**Pull request by philschatz**
Addresses naming convention described in #987. refs #931

### CODE REVIEW

**Comment by jivewise** [comment]
Oh, why did you want to take that out?

**Comment by nathanstitt** [comment]
It shouldn't be needed now that @philschatz made the earlier PR to lock the navbar to the top.  Previously we had to scroll to the top so that items weren't hidden beneath it.

**Comment by jivewise** [comment]
Gotcha, I remember using it in a previous PR at one point...thanks!

**Comment by nathanstitt** [comment]
Looks good to me

**Pull request merged**
