### PR TITLE
Add support for archiving periods to course roster

### PR DESCRIPTION
**Pull request by nathanstitt**
Goes with BE PR: https://github.com/openstax/tutor-server/pull/1112

Archiving:
screen shot 2016-06-02 at 8 31 26 pm

Restoring:
screen shot 2016-06-02 at 8 30 55 pm

### CODE REVIEW

**Comment by philschatz** [comment]
This has merge conflicts; can you rebase `master` in to here?

**Comment by philschatz** [comment]
Sometimes the screenshot says "Section" and sometimes it says "Period". Are they used consistently in the code? I think the plan is for HS courses to say "Period" and College courses to say "Section"

**Comment by nathanstitt** [comment]
@philschatz thanks for noticing the "Sections" / "Periods" wording.  The other areas were using the `CourseGroupingLabel` component which switches, but I'd messed up and used bare "Section" strings some places, probably because that's what the mockup showed.  Should be all fixed up now.

**Comment by philschatz** [comment]
Why does the cancel button appear _below_ the Archive button instead of to the right of it? Also, what happens if archiving (or unarchiving) errors? I noticed it didn't use the `<AsyncButton>` component but seemed to be a custom button component with `isArchiving`

**Comment by nathanstitt** [comment]
The mockup had "cancel" as plain text below the button, so that's what I did 😁   Yeah, it could use AsyncButton, I'll do so.

**Comment by rvnewell** [comment]
Just to confirm what we talked about in scrum: 

screen shot 2016-06-08 at 11 37 17 am

1. Cancel moved to the side of the Archive button
2. A little more padding above messaging text.
3. Lowercase "period" or "section" in messaging text.
3. Add comma in "student scores, or export." (Oxford comma all the way!)

**Comment by nathanstitt** [comment]
Made the changes, appearance is now:
screen shot 2016-06-08 at 5 18 01 pm

**Comment by rvnewell** [comment]
Looks good!  Just need to change punctuation/capitalization on the messaging, and it'll be good to go.

**Comment by nathanstitt** [comment]
Oops. The "Period" word there is actually dynamically generated depending on the course's settings.  I've changed it to be lowercase.

screen shot 2016-06-09 at 9 52 43 am

**Comment by rvnewell** [comment]
Thanks for doing that.  Last thing is that Oxford comma:  "student scores, or export."

**Pull request merged**
