### PR TITLE
perf-report using fb fixed-data-table

### PR DESCRIPTION
**Pull request by darrenmason**
image

### CODE REVIEW

**Comment by pandafulmanda** [comment]
:sunglasses:

**Comment by darrenmason** [comment]
image

**Comment by philschatz** [comment]
Should `fixed-data-table` be added to `package.json`? And can the CSS be included via `@import '../node_modules/fixed-data-table/...`?

**Comment by darrenmason** [comment]
will do

**Comment by darrenmason** [comment]
regarding remaining wip, column resize api is lightly documented so LOE is higher; I have it disabled; this could be another PR if we need it

**Comment by darrenmason** [comment]
resolved Router.Link issue with custom callback.

**Pull request merged**
