### PR TITLE
Bug/fix homework footer styles

### PR DESCRIPTION
**Pull request by pandafulmanda**
## Before
screen shot 2015-07-08 at 4 50 52 pm
screen shot 2015-07-08 at 4 51 15 pm

Homework details are all messed up

## After
screen shot 2015-07-08 at 5 12 13 pm
screen shot 2015-07-08 at 4 57 23 pm

homework details are no longer messed up

## With the info icon
screen shot 2015-07-08 at 5 16 12 pm
screen shot 2015-07-08 at 5 16 37 pm

### CODE REVIEW

**Comment by Fredasaurus** [comment]
First one looks great. Can top align all the text on the second example? having the line bounce up and down gives me the heebeegeebees.

**Comment by Fredasaurus** [comment]
We also talked about putting it in an '<i>' icon.

**Comment by Fredasaurus** [comment]
i icon, one of these days I'll remember how to escape tags here.

**Comment by pandafulmanda** [comment]
there's supposed to be an i icon only when there's a description

**Comment by Fredasaurus** [comment]
bugger.

**Comment by pandafulmanda** [comment]
@Fredasaurus I faked the descriptions and took screenshots

**Comment by Fredasaurus** [comment]
Cool. Should the i be next to the assignment title?

**Comment by Fredasaurus** [comment]
Can the "reading covers...." info always be inside the info icon? It would appear as the last part of the description if the teachers enter one, or by itself if they don't. That way we can get it off the screen but make it available to read.

**Comment by pandafulmanda** [comment]
Yes we can do that, but perhaps next sprint?

**Pull request merged**
