### PR TITLE
Back to top button for homeworks

### PR DESCRIPTION
**Pull request by jivewise**
screen shot 2016-01-06 at 12 38 26 am
screen shot 2016-01-06 at 12 38 17 am
screen shot 2016-01-06 at 12 38 07 am
screen shot 2016-01-06 at 12 37 43 am

A back to top button for the homework builder, wasn't very sure how to style it.  Suggestions/help welcome.

### CODE REVIEW

**Comment by philschatz** [comment]
@jason-holmes or @Fredasaurus any thoughts on adding this button? seems like a nice-to-have and I'd rather try to get it in (if it's wanted) soon before the code changes too much

**Comment by Fredasaurus** [comment]
I like it. Don't think we need to pipe it though.

**Comment by philschatz** [comment]
What do you mean by "pipe"? Do you mean "we shouldn't include this feature"?

**Comment by Fredasaurus** [comment]
The line between the buttons.

**Comment by jivewise** [comment]
Gotcha, you mean put the back to top button next to the Cancel or Add More button?  That might look weird, no?  I can do a screenshot if you'd like.

**Comment by jivewise** [comment]
@Fredasaurus added a few screenshots, removed the pipe between the buttons and floated the button to the right.  Let me know if you want any style changes.

**Pull request closed without merging**
