### PR TITLE
QA view: show all tags, two step filter, and question id

### PR DESCRIPTION
**Pull request by nathanstitt**
Needs to be merged & deployed along with BE PR: https://github.com/openstax/tutor-server/pull/986 

Notice that I'm displaying a pseudo text entry box (which is really just a styled div).  When I just hid the questions it wasn't easy to tell the 2-step exercises apart from one with a very short question.

image

### CODE REVIEW

**Comment by philschatz** [comment]
Is there a way we could reuse the logic for when to display free-response already in the exercise widget?

**Comment by nathanstitt** [comment]
Heh, it's actually not a textarea.  The exercise widget doesn't actually display free response, since it's just used on the teacher's HW builder.  Rather than extend the it to display a textarea that'll never actually be used, I just styled the div as to appear like one when the questions are hidden and it's displayed on QA view.

**Comment by philschatz** [comment]
Ah, `@kathi-fletcher` and @kevinburleigh75 pointed out that the logic for determining when an exercise gets a free response is not trivial ( @pandafulmanda had to jump through some hoops to get it right) and they were suggesting that this view jump through the same hoops to not accidentally show @openstax/test the wrong thing

**Comment by nathanstitt** [comment]
I'm not sure what you're referring to when you say it's not trivial.  I spoke with @pandafulmanda and @Dantemss to determine how to figure out if an exercise has a free-response or not.  They both indicated that I should check the `formats` array for the presence of `free-response`.  I added a method [hasQuestionWithFormat](https://github.com/openstax/tutor-js/pull/990/files#diff-ce4cb3be778fd8ed5807fb351cf7485aR104) to the flux store that's used for that.

Is that not the correct pattern?  Or did I mis-understand your question?

**Comment by philschatz** [comment]
I think that's probably good enough (although it seems like there might be 2 places that "check the `formats` array for the presence of `free-response`" since I only saw 1 place that calls `hasQuestionWithFormat` (maybe I missed the other place?)

**Comment by nathanstitt** [comment]
I found one other spot that could use the helper method in (TaskTeacherReviewExercise, in `components/task-teacher-review/exercise.cjsx`)  I've converted it to use it.

The student side doesn't examine the exercise for deciding when to display the task step, it looks at the task step.  See the [TaskStep store](https://github.com/openstax/tutor-js/blob/master/src/flux/task-step.coffee#L110-L114) for it's method.

**Comment by philschatz** [comment]
Looks good! Waiting for https://github.com/openstax/tutor-server/pull/986 to be reviewed /cc @jpslav

**Comment by jpslav** [comment]
That PR is merged and ready for y'all to merge when you are ready / it is non-WIP

**Comment by nathanstitt** [comment]
Yep, the BE is ready to go, sorry I forgot to remove the WIP prefix

**Pull request merged**
