### PR TITLE
Link CC scores to task review screen

### PR DESCRIPTION
**Pull request by nathanstitt**
Depends on https://github.com/openstax/tutor-server/pull/837

Two things I've noticed:

- [x] The continue button doesn't work, it's always disabled
- [x] There's no "back" button to go back to the scores report, other than re-selecting it from the menu.

screen shot 2015-11-30 at 2 08 49 pm

### CODE REVIEW

**Comment by philschatz** [comment]
maybe @pandafulmanda could help?

**Comment by pandafulmanda** [comment]
Yes, i will look into this

**Comment by nathanstitt** [comment]
Also note https://github.com/openstax/tutor-server/pull/837#issuecomment-159751034 regarding the endpoint that the task review button at the top of each column would need.  As things stand, I don't think that'll be easily implemented.

**Comment by pandafulmanda** [comment]
I've checked this again with other existing assignments for non-concept coach tasks, and things still seem to be working, so i think is ready, @nathanstitt

**Comment by nathanstitt** [comment]
Looks great!  Travis failure is due to first-of-month bug in specs

**Pull request merged**
