### PR TITLE
Set defaults for banner styles when appearance code is missing or invalid

### PR DESCRIPTION
**Pull request by nathanstitt**
image

image

### CODE REVIEW

**Comment by Fredasaurus** [comment]
Please set the size of the text in the banner to 88px and vert align as in this mockup,
http://3lwsnp.axshare.com/#p=teacher_dashboard_-_visual_design
Thanks.

**Comment by Fredasaurus** [comment]
also the font stack should be as follows:
font-family: Helvetica Neue,Helvetica,Arial,sans-serif;

**Comment by nathanstitt** [comment]
@Fredasaurus are you referring to the banner that says "Welcome to your CC dashboard?"  Or the course name banners?  I'm working on a PR to update them now, I'll ping you on it when I submit so you can review.

**Comment by nathanstitt** [comment]
So we don't want "Helvetica Bold"  used on the font stack?

**Comment by Fredasaurus** [comment]
course name banners, thanks.

**Comment by Fredasaurus** [comment]
Oh, yeah that's confusing.
font-family: Helvetica Neue,Helvetica,Arial,sans-serif;
font-weight: bold;
:)

**Pull request merged**
