### PR TITLE
Fix CC help link and add specs to it

### PR DESCRIPTION
**Pull request by nathanstitt**

### CODE REVIEW

**Comment by nathanstitt** [comment]
Looks like the invariant exception still occurs.  That's the only failure w/Travis now though

**Comment by philschatz** [comment]
I think this can be merged in the morning if the `openstax-react-components` changes are removed from this PR. Those would increase the amount of testing considerably.

**Comment by nathanstitt** [comment]
@pandafulmanda heads up that this removes the update to `openstax-react-components`.  Perhaps we can move that into a separate PR if needed.

**Comment by philschatz** [comment]
It seems the link goes to tutor zendesk even though I have a CC course


image

**Comment by nathanstitt** [comment]
I just tested with teacher01 (charles morris) and I get the CC zendesk as I should since I have at least one CC course.

Can you double check maybe?

**Pull request merged**
