### PR TITLE
Temp fix for vertical images

### PR DESCRIPTION
**Pull request by brittany-johnson**
Addresses: 
https://app.zenhub.com/workspaces/openstax-tutor-560aef617a763234615d6a0f/issues/openstax/tutor/171

https://app.zenhub.com/workspaces/openstax-tutor-560aef617a763234615d6a0f/issues/openstax/tutor/168

### CODE REVIEW

**Comment by brittany-johnson** [comment]
@nathanstitt Ready for review!

**Comment by nathanstitt** [comment]
Oh that's interesting!  Seems like it should do exactly what we want, I'm deploying to -dev so we can test

**Comment by brittany-johnson** [comment]
@nathanstitt I just checked Bio 2e on -dev but I don't think it's the latest content. The side-by-side (a) (b) images are not combined into one like Larissa said they should be. 

Also, I'm going to push one more change. On -dev, the vertical images in notes have a style that's overriding the vertical image width calc, but it wasn't overriding it locally, so I didn't see it.

**Comment by nathanstitt** [comment]
Merging so we can test on QA, we'll likely make additional tweaks later

**Pull request merged**
