### PR TITLE
Feature/not breadcrumbs

### PR DESCRIPTION
**Pull request by pandafulmanda**
milestones

 
Depends on openstax/react-components#75

Currently, milestones and multipart questions will be extremely buggy

### CODE REVIEW

**Comment by philschatz** [comment]
You changed several of the `api/**.json` files; is there a corresponding `tutor-server` PR for this or is it just client-side changes?

**Comment by pandafulmanda** [comment]
that was mostly to help with being able to navigate those steps more using just FE, there is a slight `tutor-server` change that has already been merged to master for putting `title` attribute on steps

**Comment by philschatz** [comment]
This has merge conflicts; can you rebase `master` in to here?

**Comment by pandafulmanda** [comment]
yes, am working on that after i release `react-components`, starting looking into the release because of conflicts

**Comment by pandafulmanda** [comment]
okay @philschatz it's been rebased and is ready for review again

**Comment by philschatz** [comment]
Really long assignment names seem to break this:

image

Also, should:

- the date contain something other than "X"?
- the title or calendar be clickable (and show the pull-down navigation thingy?)

image

**Comment by pandafulmanda** [comment]
1. long assignment names -- yes :) can we make that a separate bug ticket?
2. date -- we can do something other than the x, we have the x in for past due assignments only, the before due is the regular calendar icon.  i think we should ask this question to UX, and also what should the active Grid icon look like for the milestones.  i also think that these can addressed in separate prs/other tickets
3. ooh hmm...im not sure, what does @openstax/ux think about having clicking the title trigger the milestones drop down as well?  doing that on the calendar might be weird since it also shows the full due date on hover...

**Comment by jason-holmes** [comment]
2.  Date:  Why do we have to change the date on the calendar?  I think the due date should always be the due date, even if it's past due.  And I don't think we need a past due visual state on the calendar icon...should be the same state whether the due date has passed or not.
3.  We don't want to have the due date calendar icon also be the thing that activates the milestone tiles.  I think the current blue highlight of the tile icons is effective at indicating the milestones are open.

**Comment by pandafulmanda** [comment]
1. yes okay, ill fixed that.  2. okay

**Pull request merged**
