### PR TITLE
using the same animation for hover of dashboard icons and breadcrumbs

### PR DESCRIPTION
**Pull request by pandafulmanda**
screen shot 2015-05-19 at 1 44 49 pm

has drop-shadow and transition

### CODE REVIEW

**Comment by nathanstitt** [comment]
Awesome!  I also tried this awhile ago and when I used the `scale` for the dashboard it also scaled the background making the icon appear to have a weird square border.  Wonder what I was doing wrong?

**Comment by pandafulmanda** [comment]
ah! i snuck in a `border-radius: 50%;` [here](https://github.com/openstax/tutor-js/pull/279/files#diff-1aab5344055dab8ca418c01be9fe1412R59)

**Comment by nathanstitt** [comment]
Aha, clever clever!  This is really cool, the two implementations were so close it really makes sense to combine them.

**Comment by philschatz** [comment]
Thanks!

**Pull request merged**
