### PR TITLE
learning guide - updated design/ui, links, expanding panels

### PR DESCRIPTION
**Pull request by darrenmason**
image

### CODE REVIEW

**Comment by Fredasaurus** [comment]
Looking good, almost there....

**Comment by philschatz** [comment]
It seems the buttons do not go to a new set of practice problems

**Comment by philschatz** [comment]
hmm, looks like there are some floating issues with long chapter titles:

image

**Comment by Fredasaurus** [comment]
Here is how I handle that. Note the two line title. If it is any longer we can truncate.
screen shot 2015-07-14 at 5 34 32 pm
http://mockups.openstax.org/Tutor_MVP_beta_release/start.html#p=learning_guide_v2

**Comment by darrenmason** [comment]
ill adjust for 2 lines and the truncation width just needs a few more px width.

**Comment by darrenmason** [comment]
image

**Pull request merged**
