### PR TITLE
Change student-id color to #999999 (neutral-lite)

### PR DESCRIPTION
**Pull request by nathanstitt**
per @rvnewell on https://github.com/openstax/tutor-js/pull/1356#issuecomment-248728112

screen shot 2016-09-26 at 9 10 40 am

### CODE REVIEW

**Comment by Fredasaurus** [comment]
I believe @rvnewell wanted to change the color of just the name or the ID, so they didn't carry equal weight.

**Comment by nathanstitt** [comment]
Hm, no pretty sure he meant to change both https://github.com/openstax/tutor-js/pull/1356#issuecomment-248728112  maybe we could just change the student id though, that might be better

**Comment by rvnewell** [comment]
Yes, to confirm:  Please make the student ID #99999.  The idea is for the ID not to get in the way of scanning the names. Teachers will be scanning the names much more often than the ID's.

**Comment by nathanstitt** [comment]
Thanks @rvnewell, i've updated code and screenshot to reflect that only student id should be #99999 
Sorry for the confusion

**Comment by rvnewell** [comment]
Thanks, @nathanstitt !

**Pull request merged**
