### PR TITLE
Feature/link preview

### PR DESCRIPTION
**Pull request by pandafulmanda**
# Media/link viewer
* works for both iReadings and reference book
* Especially useful for steps where the image is in another step

The jumping links was driving me straight up nuts
nuts!
addresses #758

## To do
- [x] tests
  - [x] the media flux
  - [x] media previewer component
  - [x] tutor-overlay component
- [x] work out details of UI with @Fredasaurus
  - [x] when media is huge-mungus
    * tables will be truncated/scrollable previews
  - [x] when media is already in viewport
    * media is highlighted like regular targeted
  - [x] when link is clicked
    * will scroll using #724 if media on page
    * will keep previewer open until click blur if media not on page

### Table preview
screen shot 2015-09-08 at 6 23 08 pm

### If media is not even on the current page
screen shot 2015-09-08 at 6 22 42 pm
#### links externally to ref book, but shows preview on hover
screen shot 2015-09-15 at 5 50 41 pm

### If media is not visible/partially visible
screen shot 2015-09-08 at 7 50 47 pm

### If media is more than half visible
screen shot 2015-09-08 at 7 51 32 pm

### For table, if partially visible
screen shot 2015-09-10 at 5 07 30 pm

### Scrollable inner content, esp useful for big tables
screen shot 2015-09-10 at 8 02 13 pm
#### Scrollable for figures as well
screen shot 2015-09-15 at 6 39 03 pm

### Is smart about where to open up viewer
opens to the left when too close to the right
screen shot 2015-09-11 at 7 21 25 pm

### CODE REVIEW

**Comment by kathi-fletcher** [comment]
So nice!

**Comment by philschatz** [comment]
This looks really nice! I'm going through and testing it 1st and then will go through and review the code.

**Comment by pandafulmanda** [comment]
great thanks!  I just had to revert because i was merging master from when #724 was accidentally in master

**Comment by philschatz** [comment]
If a figure is large, the popup becomes unusable:

image

Also, does the rule of "only pop up if the element is not visible on the page" make sense? It seems like there are some corner cases where students would get confused (like if only a couple pixels of the figure/table are visible)

**Comment by pandafulmanda** [comment]
how much the figure has to be showing on the page is adjustable -- right now, its like at least 120px or soemthing

**Comment by Fredasaurus** [comment]
Small sample size, but we tested it out with Sonja. She got it.

**Comment by philschatz** [comment]
I tried the "If media is not even on the current page" example but clicking on the link did not open the ref book in a new tab; should it?

**Comment by pandafulmanda** [comment]
no, the popover should stick and stay open until you blur off the link

**Comment by kathi-fletcher** [comment]
How close is this to ready? Should I add to Sprint 18?

**Comment by pandafulmanda** [comment]
this is very close to ready, I think it can go in Sprint 18

**Comment by philschatz** [comment]
yeppers!

**Comment by pandafulmanda** [comment]
closing in favor of combo PR #767

**Pull request closed without merging**
