### PR TITLE
Show exercise uid on HW builder

### PR DESCRIPTION
**Pull request by nathanstitt**
TODO:
 * [x] Display on HW builder
 * [x] Student i-reading questions
 * [x] Student hw questions
 * [x] Student practice widget

Homework Builder:
screen shot 2015-07-28 at 9 57 43 pm

Multiple choice question.  The same component is used for both readings, homeworks, and practice exercise. The UID is displayed identically on them all.
screen shot 2015-07-29 at 10 29 09 am

### CODE REVIEW

**Comment by philschatz** [comment]
Can you put the id in the exercise builder in the bottom-right corner (like in the student view)?

**Comment by nathanstitt** [comment]
@philschatz Yeah, that'd be an easy change to make (and would make the code cleaner), but the mockup shows the id mixed in with the tags.  Should I go ahead?

**Comment by philschatz** [comment]
@Fredasaurus thoughts on where/how these id's should be displayed?

**Comment by Fredasaurus** [comment]
I think it looks fine where it is. Do we need to label it as "ID" in the second example?

**Comment by philschatz** [comment]
I think light grey is sufficient but that's your call ; ) merging for now so Greg has the data sooner

**Comment by Fredasaurus** [comment]
Cool.

**Pull request merged**
