### PR TITLE
printer safe reference book

### PR DESCRIPTION
**Pull request by darrenmason**
regarding task:  https://www.pivotaltracker.com/story/show/102331932

adjustments to clean up printing of refbook

chrome print preview:

image

ie11 print preview:

image

### CODE REVIEW

**Comment by philschatz** [comment]
When the Table of Contents is expanded the book is still shifted to the right (see the left padding in the screenshot):
 
image

**Comment by darrenmason** [comment]
prints full width now, regardless of menu state;  tested in IE11, Saf8, Chrome 45, FF 40

**Comment by philschatz** [comment]
Thanks! The left margin does not appear but when I look at 1.2 I noticed some of the learning objectives are above the top margin (in Chrome):

image

Any ideas why?

**Comment by darrenmason** [comment]
should be aligned now:

image

**Pull request merged**
