### PR TITLE
Fix for chapter sections on stats

### PR DESCRIPTION
**Pull request by pandafulmanda**
screen shot 2015-05-20 at 6 40 56 pm

@nathanstitt @darrenmason i changed something in learning guide and I checked that it's still working, but please confirm

uses openstax/tutor-server#301

### CODE REVIEW

**Comment by philschatz** [comment]
:+1: 

Should non-React components (and mixins) live outside of `src/components`?

**Comment by pandafulmanda** [comment]
oh hhhhmmm...i dunno, i dont think i have an opinion either way.  if so, separate PR?  sounds like a broader discussion...what about mixins that are currently group inside a folder in components?

**Comment by philschatz** [comment]
The question was more for @darrenmason and @nathanstitt since the learning guide is the only non-Component so far; but yes, moving it would be a separate PR since the styling would need to move as well.

**Comment by darrenmason** [comment]
I don't see it as an issue, however not sure how we are defining 'non-react'

**Comment by darrenmason** [comment]
makes sense to pull out sectionFormat function

**Pull request merged**
