### PR TITLE
link to review page from perf report

### PR DESCRIPTION
**Pull request by pandafulmanda**
screen shot 2015-07-07 at 12 22 28 pm

### CODE REVIEW

**Comment by Fredasaurus** [comment]
Why is everything orange?

**Comment by nathanstitt** [comment]
That's the "standard" Tutor link color.  Should it be changed just here or do you think all instances should be?  I know quiet a few other places also use it.  Reference book links, and some of the learning guide come to mind.

**Comment by nathanstitt** [comment]
And.. I thought you'd commented on my course admin PR, not the Perf report.  My answer's still valid though since the course admin links are also orange. :grinning:,

**Comment by Fredasaurus** [comment]
Ha, OK. Standard link color should be #00c1de.

**Pull request merged**
