### PR TITLE
Guide drilldown fix

### PR DESCRIPTION
**Pull request by darrenmason**
This fixes drilldown to chapter bug and detects chapter_section array or string

### CODE REVIEW

**Comment by philschatz** [comment]
When I click "4" and "View this chapter" the label for the chart seems wrong. It says both "Acceleration" (wrong chapter) and "Show All Chapter 1 Placeholder" (should be "Show All Chapters")

image

**Comment by philschatz** [comment]
Thanks!

**Comment by darrenmason** [comment]
image

**Comment by darrenmason** [comment]
title fix screenshot

**Pull request merged**
