### PR TITLE
Update and fix shared components

### PR DESCRIPTION
**Pull request by pandafulmanda**
- [x] Clean up duplicate styles
- [x] Replace local copies of components with shared components
  * `ChapterSectionMixin`
  * `GetPositionMixin`
  * `ResizeListenerMixin`
  * `SmartOverflow`
- [x] update tests as needed
- [x] update `react-components` again after openstax/react-components#31 and openstax/react-components#33 are merged

### CODE REVIEW

**Comment by pandafulmanda** [comment]
ready for review, just waiting on a final component package update after openstax/react-components#31 is merged

**Comment by pandafulmanda** [comment]
now needs an update after openstax/react-components#36 is merged

**Comment by philschatz** [comment]
Howdy! Can you merge conflicts? I think the other PR's this depends on are merged

**Comment by pandafulmanda** [comment]
now needs an update after  openstax/react-components#38 is merged

**Comment by philschatz** [comment]
@gregfitch When is the next planned round of doomsday-ish testing? This _shouldn't_ break anything but it **does** touch a bunch of screens (mostly the ones that display exercises)

**Pull request merged**
