### PR TITLE
Homework builder styling cleanup

### PR DESCRIPTION
**Pull request by dak**

### CODE REVIEW

**Comment by philschatz** [comment]
Thanks! Can you include screenshots in the PR description (or mark the title WIP if it's not complete yet).

It seems the `X` button for the panel is no longer white or lined up on the right hand side:
image

Long exercise text seems to obfuscate the Move-Up/Down/Remove arrows (and the white exercise number is barely visible):
image

**Comment by dak** [comment]
@philschatz Yeah, I'm going to fix the Add Homework Assignment panel in this next PR.  It looks and behaves like a Dialog, but unfortunately is not a Dialog.

**Comment by philschatz** [comment]
@jivewise : Is there a rason why the **Add Homework Assignment panel** isn't a dialog?

**Comment by philschatz** [comment]
any objections @jivewise ?

**Comment by jivewise** [comment]
No objections.

**Pull request merged**
