### PR TITLE
concept coach logout link

### PR DESCRIPTION
**Pull request by darrenmason**
regarding task: https://www.pivotaltracker.com/n/projects/1156756/stories/108517582

### CODE REVIEW

**Comment by philschatz** [comment]
Does tutor-server part work too (redirect to `cc.openstax.org`) when that param is set?

**Comment by darrenmason** [comment]
tested with https://github.com/openstax/tutor-server/pull/823, not redirecting

**Comment by nathanstitt** [comment]
:+1: Works with local accounts running.  Both `cc=true` or `cc=1` parameters are accepted.

**Comment by philschatz** [comment]
yay!

**Pull request merged**
