### PR TITLE
record useful replay data for developers/QA

### PR DESCRIPTION
**Pull request by philschatz**
# For Folks reporting bugs

### [Demo it in action here](http://philschatz.com/gh-board/?collect=true) (see the `[[2]]` in the bottom-right)

1. Add `?collect=true` to the end of any URL to start collecting a replay log.
2. Once you hit a bug/problem, just push a button on the bottom-right corner of the page and the log (plus your browser info) is copied to the clipboard (using [clipboard.js](https://github.com/zenorocha/clipboard.js))

(this code can be used on any site. Like `cnx.org`) 

The logging UI and controls are found in the **bottom-right corner** of the window which shows the current number of messages logged:

image

When you hover over the log count, the control panel opens up:

image

The buttons:
- <kbd>X</kbd> Stop all the logging and instrumentation
- <kbd>Clear</kbd> clear the log (if you are starting a new test)
- <kbd>Copy</kbd> copy the log and :sparkles: _Browser Info_ :sparkles:  to the clipboard (and eventually the exact manifest/config of the server)

Something like the following will then be on your clipboard which you can paste into the ticket tracker of your choice (it also contains the request/response JSON with the server):

# For Developer Folks

```js
window.__REPLAY_LOG = [
  ["CLICK", "div.collapse.navbar-collapse"]
  ["XHR", "start", "GET", "/api/tasks/226"]
  ["XHR", "load",  "GET", "/api/tasks/226", 200, "{'id':...}"]
  ["CLICK", "button.async-button.continue[type='button']>span", "Continue"]
  ["HISTORY", "change", "/courses/3/tasks/226/steps/2/"]
  ["XHR", "start", "GET", "/api/steps/3653"]
  ["XHR", "load", "GET", "/api/steps/3653", 200, "{'id':'3653',...}"] # <-- response JSON
  ["CLICK", "div.answer-letter"]
  ["HISTORY", "pop","/courses/3/tasks/226/steps/1/"]   # <-- clicked browser back button
  ["UNCAUGHT", "data is undefined", "index.js", 1000, 10] # <-- uncaught JS errors
  ["HISTORY", "unload"]    # <-- Either refresh was clicked or the user went to another page

# ["CONSOLE", "ERROR", "React: Caught Exception nullpointer..."]
]
```

# TODO:

- [x] add `clipboard.js` functionality
- tell teachers so they can help report too! (or wire it up to zendesk to automatically send)

# Thoughts

We could send this to something like papertrail whenever a user (it would need to be turned on all the time though):

1. gets a server exception
2. has a JavaScript exception
3. clicks the zendesk link

We could also randomly turn it on and see what elements students click on (maybe for Google Analytics?)

### CODE REVIEW

**Comment by jivewise** [comment]
Definitely pretty cool, does it also record post data?

**Comment by nathanstitt** [comment]
:+1: I like it a lot.  Just tried it on Chrome and Safari on mac and IE 11 on windows.  Safari requires the command-c (as noted).    Windows popped up an alert asking if I wanted to give the webpage access to the clipboard.  Once I granted it permission it worked fine.

Most importantly I didn't notice any app failures.  Since `recordo` (cool name) works by overriding `xhr` and other system events that made me nervous at first.  It all seems to be working well though.

**Comment by philschatz** [comment]
@jivewise Yep, here's changing a period:

```js
    ["USER:CLICK", "a>span", " Change Period"],
    ["USER:CLICK", "a[href='#'][role='button']", "2nd"],
    ["XHR:START", "PATCH", "/api/students/8", "{\"period_id\":\"2\"}"],
    [
      "XHR:LOAD",
      "PATCH",
      "/api/students/8",
      200,
      {
        "id": "8",
        "period_id": "2",
        "role_id": "9",
        "first_name": "Rabbit",
        "last_name": "Angstrom",
        "name": "Rabbit Angstrom",
        "deidentifier": "f55e29ad",
        "is_active": true
      }
    ]
```

**Comment by jivewise** [comment]
Awesome, playing around with it a bit now in tutor-dev.  Looks great so far

**Pull request merged**
