### PR TITLE
Dashboard hw status icons

### PR DESCRIPTION
**Pull request by nathanstitt**
screen shot 2015-07-18 at 8 04 15 pm

### CODE REVIEW

**Comment by nathanstitt** [comment]
@Fredasaurus If you like these tooltips, we could also use them on the learning guide as well.

**Comment by philschatz** [comment]
Travis is failing ; (

**Comment by nathanstitt** [comment]
That did it.  I'd removed a require statement that it needed on the hw.  Weird that the error was an invariant one though

**Comment by philschatz** [comment]
It's still failing ; (

**Comment by nathanstitt** [comment]
Ok, Finally.  I think the extra space that the new icons where inserting into the DOM was causing the specs to be non-deterministic.   I also rebased from master since it conflicted with the other PR to not work unopened tasks.

**Comment by Fredasaurus** [comment]
Looks good.

**Pull request merged**
