### PR TITLE
upload jest code coverage to codecov.io

### PR DESCRIPTION
**Pull request by philschatz**
Inspired by [cnx-recipes#136](https://github.com/Connexions/cnx-recipes/pull/136), this generates code coverage for each of `tutor`, `exercises`, `coach`, and `shared` using https://facebook.github.io/jest/docs/configuration.html#collectcoveragefrom-array

You can see the results at https://codecov.io/gh/openstax/tutor-js/commits and then click a commit, and then click the "Files" tab near the top

Thanks @nathanstitt for the how-to! It was surprisingly simple!

# Questions

- [x] should I also add a config for `shared`?
- [x] will codecov.io properly OR all the coverage files from the various builds together?
- [ ] should I change the inclusion/exclusion patterns (do they spend extra time instrumenting files that do not end up being run?)
- [ ] should the karma code get removed?

# Screenshots

image

image

refs openstax/napkin-notes#68

### CODE REVIEW

**Comment by nathanstitt** [comment]
Looks great @philschatz - thanks!

I'd say go ahead and remove the karma configs, we've been using Jest long enough without problems that I think there's no reason to keep that around.

I don't think the inclusion/exclusion should need tweaked, but feel free to run some tests to find a speedier setup if you want 😁

**Comment by philschatz** [comment]
What if karma is removed in a separate PR? That way it would be easier to search for it if folks wanted to pick it back out for something like selenium tests or something

**Comment by nathanstitt** [comment]
Sounds good, we'll merge after the next release, thanks @philschatz

**Comment by nathanstitt** [comment]
Thanks @philschatz !

**Pull request merged**
