### PR TITLE
adjust code to hide modal earlier

### PR DESCRIPTION
**Pull request by nathanstitt**
Get the drop question modal offscreen as soon as visible items are updated

### CODE REVIEW

**Review by Dantemss — COMMENTED** [review]
Hmm not sure if I'm a fan because this means the modal disappears before saving is complete so what if saving silently fails?

**Comment by nathanstitt** [comment]
no it disappears as soon as *saving* is complete.  It then refreshes the scores in the background.  If that fetch does fail then the error modal will still appear

**Comment by Dantemss** [comment]
Isn't it hiding before the exclusions are saved though?

**Comment by nathanstitt** [comment]
oh right, so we are.  THat's also fine though because if exclusions fail we show the error modal

**Comment by nathanstitt** [comment]
yah the only way to not show the modal is to pass in the `ignoreErrors` flag to `api.request`. The only spot we do that currently is for response validator

**Pull request merged**
