### PR TITLE
Add recovery to coreGroups

### PR DESCRIPTION
**Pull request by nathanstitt**

### CODE REVIEW

**Comment by philschatz** [comment]
Now that this is deployed (:tada:) can you merge conflicts (please don't rebase!)

**Comment by nathanstitt** [comment]
hm, we'll need https://github.com/openstax/react-components/pull/42 merged first.  If I merge master it'll pull in a version without that PR.

**Comment by philschatz** [comment]
ah, good point! merged the other PR :smile:

**Comment by nathanstitt** [comment]
@philschatz ok, merged in master and this is now conflict free

**Pull request merged**
