### PR TITLE
Display "No Exercises" message when loading fails

### PR DESCRIPTION
**Pull request by nathanstitt**
Current error dialog is below, @openstax/ux please review and advise if it should be changed

Goes with BE PR: https://github.com/openstax/tutor-server/pull/1192, but can be merged independently 

screen shot 2016-07-18 at 10 49 38 am

### CODE REVIEW

**Comment by jason-holmes** [comment]
This will show anytime there are not problems to display (i.e., homework, practice, reading whatever) right?  If so, then a more generic message like: "There are no problems to show for this topic." [OK]

**Comment by nathanstitt** [comment]
Spec failures are unrelated - HW builder specs appear to be testing using date math that's failing

**Comment by pandafulmanda** [comment]
ugh will have to look into that at some point.

**Comment by nathanstitt** [comment]
oh, I was actually incorrect on the spec failures - sorry!  It was the error handler spec that wasn't clearing.  I fixed that in the last commit

**Pull request merged**
