### PR TITLE
Remove tiny "TM" from logo

### PR DESCRIPTION
**Pull request by nathanstitt**
It's too small to be read.  I didn't notice it at all last night on the laptop screen.  This morning when I plugged into my monitor it looked like a dirt spec.

Before
screen shot 2015-12-02 at 9 55 40 am

after:
screen shot 2015-12-02 at 9 51 08 am

### CODE REVIEW

**Comment by Fredasaurus** [comment]
It has to be there. Even it you can't read it.

**Comment by Fredasaurus** [comment]
We could make it bit larger.

**Comment by philschatz** [comment]
Then I propose we make it transparent :smirk:

**Comment by nathanstitt** [comment]
Hm,  How about if we leave it on, but size the background image so that it's not visible?

**Comment by Fredasaurus** [comment]
Oooooh, it was there the whole time!

**Comment by nathanstitt** [comment]
Done :)  Original logo is restored but looks better now

**Pull request merged**
