### PR TITLE
Add bootstrap for offerings

### PR DESCRIPTION
**Pull request by nathanstitt**
was stopping tutor from booting

### CODE REVIEW

**Comment by camliu89** [comment]
@nathanstitt I think this is what I was trying to fix in my PR.

**Comment by camliu89** [comment]
👍

**Review by jivey — APPROVED** [review]

**Comment by jivey** [comment]
The spec failure seems to be from something flaky, the screenshot when the selector failed was:

image

**Comment by nathanstitt** [comment]
I'm going to merge this so the main tutor app boots, will make a followup with the role fix for specs in a bit

**Pull request merged**
