### PR TITLE
Updated Assignment Settings

### PR DESCRIPTION
**Pull request by jivewise**
Updates which settings are editable on the front end after an assignment is published and is open.

screen shot 2016-06-02 at 11 51 45 pm
screen shot 2016-06-02 at 11 51 36 pm

Also includes changes to student dashboard, showing deleted tasks and hide task buttons:

pasted_image_at_2016_06_10_04_11_am

For: https://www.pivotaltracker.com/story/show/115959401

### CODE REVIEW

**Comment by jivewise** [comment]
Before merging this, merge #1094 into here.

**Comment by philschatz** [comment]
After changing the feedback on an assignment that has already closed I got:

image


Also, after deleting an assignment and going back to the URL for the assignment I see a 404 (maybe that's ok)

image

**Comment by jivewise** [comment]
Hm, @openstax/ux should the feedback field be updatable if the assignment is past due?  If not, I can disable it.  Otherwise, it will have to be a backend fix.

**Comment by jason-holmes** [comment]
Feedback field should not be updatable after the assignment is due.  Please disable.

**Comment by philschatz** [comment]
merging now for testing but still need @openstax/ux feedback and maybe we can create a new PR

**Comment by philschatz** [comment]
Does @openstax/tutor-be give enough information to tell that an assignment's due date has already passed? Aside from doing date-math in the browser?

**Comment by jivewise** [comment]
I believe we have an isPastDue helper on the flux store that we can use, I'll add that in a separate PR.

**Pull request merged**
