### PR TITLE
Add tests for Exercise selection

### PR DESCRIPTION
**Pull request by jivewise**
Migrating some of the tests from #957, it was easier to create a new PR than to rebase.

### CODE REVIEW

**Comment by philschatz** [comment]
`Error: Cannot find module './exercise-selector'`

**Comment by jivewise** [comment]
Sorry, I forgot to push this module somehow.

**Comment by philschatz** [comment]
I get the following error on dev (maybe I should run a newer version of tutor-server?):

```
$ SERVER_URL="https://tutor-dev.openstax.org" npm run test-integration

  1) Assignment Publishing Tests Can select exercises:

      AssertionError: expected 1 to equal 2
      + expected - actual

      -1
      +2
      
      at test-integration/task-plan/homework.coffee:55:33
      at Array.forEach (native)
  From: Task: Assignment Publishing Tests Can select exercises
      at Array.forEach (native)
```

**Comment by jivewise** [comment]
For some reason, I had to add two clicks in a row to make sure that the exercises are selecting correctly.  I think it may have something to do with the way we're handling the hover state or click event?

**Comment by philschatz** [comment]
That's odd. I've noticed click issues when selecting the chapters in the HW builder before. Maybe @pandafulmanda could help diagnose?

**Comment by philschatz** [comment]
Any updates on this? Travis still seems to be failing

**Comment by jivewise** [comment]
I'm not sure why this test is failing, I'll try to get some help from @pandafulmanda today or tomorrow.

**Comment by philschatz** [comment]
Actually, I re-ran travis and it passed. let me re-run it again

**Pull request merged**
