### PR TITLE
add server 40x and 50x errors to show to the user

### LINKED ISSUE #560: Display error messages to users when 500's occur
Pop up a modal (or similar) for when a 500 error occurs, with standard "An error occurred" messaging, the returned error_id, and a help desk link?  We're going to be 500'ing if the practice widget ends up being empty (which has happened and shouldn't be happening), and it'd be nice if the 500 showed up in more than just the console.

### PR DESCRIPTION
**Pull request by philschatz**
fixes #560 

screen shot 2015-08-07 at 1 04 19 pm

### CODE REVIEW

**Comment by jason-holmes** [comment]
Pending Jeff's response to my email (PS was cc'd) the link to "Submit a Request" in Zendesk is, https://openstaxtutor.zendesk.com/hc/en-us/requests/new

**Comment by philschatz** [comment]
Should the whole page (behind the modal) get replaced with the error text? I logged in as a student and went to the Reading builder URL and clicked "Publish":

image

**Comment by nathanstitt** [comment]
That's really weird.  I just tried the same thing (logged in as student and attempted to publish).  The error message was confined to the dialog as it should be for me.  Did you notice any console errors or anything?

screen shot 2015-08-09 at 8 09 59 pm

**Comment by nathanstitt** [comment]
@philschatz Looking at your console, I see quite a few warnings regarding the modal.  I.E. "title prop is deprecated, use Modal.Title".  I don't receive any of those.  I'm running React Bootstrap version `0.22.6`, even after a `npm update react-bootstrap`   Can you let me know what version you've got?

**Comment by philschatz** [comment]
yep, I'm using `0.22.6` as well (though I did try to update react-bootstrap a couple weeks ago). I went to that URL and got the same error:

image

**Pull request merged**
