### PR TITLE
Select Topics Sorting

### PR DESCRIPTION
**Pull request by jivewise**
screen shot 2015-06-02 at 9 59 04 am
screen shot 2015-06-02 at 9 59 53 am

### CODE REVIEW

**Comment by philschatz** [comment]
can you disable/hide the arrows at the top/bottom of the list? @Fredasaurus preferences?

**Comment by Fredasaurus** [comment]
Yeah, up on top, and down on bottom is cool.

**Comment by philschatz** [comment]
@Fredasaurus should they be disabled or removed?

**Comment by Fredasaurus** [comment]
aaaaah. I say removed.

**Comment by philschatz** [comment]
any update on this?

**Comment by jivewise** [comment]
Done now, had some weird logic between the exercises and how it was affecting readings when removing topics.  Should be fixed now.

**Pull request merged**
