### PR TITLE
add course listing with role

### PR DESCRIPTION
**Pull request by philschatz**
# Student dashboard

Each panel is a course. Note the button "Task List (Student)". That is specific for students (role).
image

# Teacher dashboard

Note the button "Plan List (Teacher)". That is specific for teachers (role).

image

If the teacher can be a student as well (2 roles) then there would be 2 buttons, one for the student, and one for the teacher.

Also, refactor the course store

TODO:

- [ ] add tests

### CODE REVIEW

**Comment by pandafulmanda** [comment]
Looks awesome!  Practices not currently working, wanted to fix it now, but I have to get going.  I can look at this tonight.

**Comment by pandafulmanda** [comment]
_loaded in course.coffee doesn't know when it needs to load the practice --- obj.practice doesn't become true.  We could change lines 20 - 23 to:

```
  _loaded: (obj, courseId) ->
    if obj.steps
      @_loadedPractice(obj, courseId)
    obj
```

which works, but is not ideal.  Also, will need to look into this more, but while new practice gets created when the "Do more practice" button gets clicked, the practice view does not update.

**Comment by philschatz** [comment]
Creating a new practice (and stepping through it) seems to work for me. I'm using https://github.com/openstax/tutor-server/commit/586ca087e04414af0a2d241c13a941eb31cefee1

and logged in as `student` (not `student_*`)

**Comment by jpslav** [comment]
@philschatz is also using the latest sprint:008 rake task

**Comment by pandafulmanda** [comment]
Hmm okay, I was using openstax/tutor-server@6e5f839b96707b3e5543c282894d9da98018580d (openstax/tutor-server#126), so I'll try again.

I guess I wasn't very specific about when it doesn't seem to be working.  The happy path of clicking the Practice button from the task page works for me as well.  However,

1. Going to the FE practice url directly without clicking the button (i.e. when you refresh the page)
  * GET is performed and returned as expected
  * Course store **does not** load result as a practice
1. Clicking "Do more practice" to try to load another additional practice
  * POST is performed and returned as expected
  * React component **does not** re-render

I'll try with openstax/tutor-server@586ca087e04414af0a2d241c13a941eb31cefee1 and also with openstax/tutor-server@cfcff070a4e42f6d4cae78f4df5fd1e4230958cd (current master) before making any changes.

**Comment by pandafulmanda** [comment]
Tried at both openstax/tutor-server@586ca087e04414af0a2d241c13a941eb31cefee1 and openstax/tutor-server@cfcff070a4e42f6d4cae78f4df5fd1e4230958cd (current master), same issue. branching and making edits.

**Comment by philschatz** [comment]
What would it take to fix those issues?

**Comment by pandafulmanda** [comment]
I don't think much, working on it in https://github.com/openstax/tutor-js/tree/course-list-edits

**Pull request merged**
