### PR TITLE
Datepicker Auto Expand

### PR DESCRIPTION
**Pull request by jivewise**
Another PR for date picker auto-expand.

### CODE REVIEW

**Comment by philschatz** [comment]
Clicking on "Today" in the calendar does not autofill in the date when creating an iReading or Homework. Other than that it seems to work!

**Comment by jivewise** [comment]
I thought we weren't going to let teachers create homeworks that with a due date of today.  It seems like the minimum for that should be at least tomorrow.

**Comment by philschatz** [comment]
@Fredasaurus thoughts on dates? and if today is not selectable, @pandafulmanda what would be needed to change the calendar?

**Comment by Fredasaurus** [comment]
Same day is aok.

**Comment by philschatz** [comment]
Maybe @jpslav has thoughts (since the assignments will be cron jobs)?

**Comment by jpslav** [comment]
Assignments aren't going to be cron jobs per se, but they will be running in the background (immediately after someone hits "publish").  Same day assignments are potentially not good because the current default due time is 7am (chosen to avoid ambiguity about what "midnight" means).  So if someone hit the publish button at 8 am with a due date of today, the assignment would be past due immediately.  Even when we had a default due time of midnight, kef's assumption was that that meant the first second of a particular day (not 11:59:59pm), in which case there's no allowance for publishing something that is due today.

Kef/LAT have requested explicit due times post alpha, fwiw.

Sorry to be behind on this one.

/cc @kevinburleigh75

**Pull request merged**
