### PR TITLE
Feature/cal nav by route

### PR DESCRIPTION
**Pull request by pandafulmanda**
screen shot 2015-06-22 at 7 33 54 pm

a nice to have.

### CODE REVIEW

**Comment by philschatz** [comment]
I like the ability to specify the month in the calendar (maybe @jivewise could send back to the correct month on save or just go to history `-1`).

How much work would it be to only include the year and month? I imaging each `transitionTo` call would have to handle it. Also, I wonder if `http://localhost:3001/courses/1/t/calendar/months/06-99-2015/` should do something other than:

image

**Comment by pandafulmanda** [comment]
ah! did think about that edge case

**Comment by pandafulmanda** [comment]
fixed the edge case, calendar should now redirect to today if an invalid date is put in the url

**Comment by pandafulmanda** [comment]
need to take out some sneaky stuff that I did with abusing setting the value of nextState[some property] to values in willComponentUpdate

**Comment by pandafulmanda** [comment]
@philschatz there should be no more tomfoolery

**Pull request merged**
