### PR TITLE
Fix/teacher review coach

### PR DESCRIPTION
**Pull request by pandafulmanda**
See [ticket](https://www.pivotaltracker.com/story/show/110131688) for full details

### The review for coach functions like the one in actual coach
screen shot 2016-02-18 at 12 46 31 pm

### CODE REVIEW

**Comment by philschatz** [comment]
Thoughts @jason-holmes or @Fredasaurus ?

**Comment by pandafulmanda** [comment]
@jason-holmes @Fredasaurus -- the alternative would be to have the teacher's view of the students work link to a view actually inside webview, on coach.

**Comment by philschatz** [comment]
Do the "Return to 1.1" or "Continue to" links do anything? If not, I'm wondering how important it is to make the view look _exactly_ like the student view

**Comment by pandafulmanda** [comment]
They are disabled here so they don't do anything

**Comment by pandafulmanda** [comment]
spoke with @jason-holmes and he agreed with you that the links are extraneous so I've made an update

**Pull request merged**
