### PR TITLE
Student Scores - updated text and labels

### PR DESCRIPTION
**Pull request by darrenmason**
https://www.pivotaltracker.com/story/show/109459986

image

- [x] review info text
- [x] student id label
- [ ] chapter/section prepend to headings titles
- [ ] order chapter/sections as ordered in class performance page

### CODE REVIEW

**Comment by philschatz** [comment]
Is there enough information in  the JSON to provide the section numbers? Also, I think BE should control the order of the columns, @jpslav ?

**Comment by darrenmason** [comment]
We should add chapter/section numbers to the headings

**Comment by philschatz** [comment]
@jpslav Could the chapter/section numbers be included in the assignment title? That way CC assignments are still similar to reading/HW assignments.

**Comment by philschatz** [comment]
@darrenmason mind if I merge this in now and revisit the remaining issues in a separate PR?

**Comment by darrenmason** [comment]
@phil nope

**Comment by jpslav** [comment]
Yes should be able to do that here...

https://github.com/openstax/tutor-server/blob/master/app/subsystems/tasks/get_cc_performance_report.rb#L88

I think page has a book_location field that could be prepended after
conversion to string.

How important to do this?

**Comment by philschatz** [comment]
@kathi-fletcher How important is it to have the chapter and section number in the Student Scores table headings? It would require a change in `tutor-server` to prepend that information each title of a CC "assignment"

**Pull request merged**
