### PR TITLE
New footer logic

### PR DESCRIPTION
**Pull request by jivewise**
not-published
published-not-opened
published-and-opened
- [x] updated footer to include new logic
- [x] modified api to post/patch even for publish
- [x] removed publish button from exercise summary bar
- [x] update tests for footer

I'll add the async button code in another PR

### CODE REVIEW

**Comment by jason-holmes** [comment]
Jing,
We’re going to have to come up with a different treatment for that instructional copy under the buttons…possibly a hover tooltip on the buttons or maybe an Info icon that teachers can click to get help on what the buttons do. Let’s plan on addressing this in the next sprint.

-------
Jason Holmes, Ph.D.
User Experience Manager
OpenStax | OpenStax.org
(713) 893-1326

**Comment by philschatz** [comment]
Can you merge from master (I think it's only CSS conflicts)?

**Comment by jivewise** [comment]
Sure.

**Comment by philschatz** [comment]
These commits are also contained in #395

**Pull request closed without merging**
