### PR TITLE
chart, panel resizing

### PR DESCRIPTION
**Pull request by darrenmason**
chart resizes to configurable min/max width.  I have added a function to dynamically resize footer panel position but have not been able to cleanly bind/unbind to resize event inside child component.  The issue basically with being unable to unbind the resize event on unmount of component.

### CODE REVIEW

**Comment by philschatz** [comment]
Is this still being worked on or is this blocked on something?

**Comment by darrenmason** [comment]
still working on this one, not sure if i have a fix for resize listener issue

**Comment by darrenmason** [comment]
thanks @nathanstitt :+1:

**Comment by nathanstitt** [comment]
NP at all, you were like 99.9 there :)

**Pull request merged**
