### PR TITLE
fix step footer when viewing as teacher

### PR DESCRIPTION
**Pull request by pandafulmanda**
screen shot 2015-07-06 at 12 13 04 pm

### CODE REVIEW

**Comment by philschatz** [comment]
Hmm, might https://github.com/openstax/tutor-server/pull/409 fix part of this?

**Comment by philschatz** [comment]
and @darrenmason does the JSON change to `/api/courses/1/performance.json` match the format you're expecting?

**Comment by pandafulmanda** [comment]
no, ```/api/courses/1``` is the route that is missing the roles and causing problems.  ```/api/user/courses``` is the one with all courses and roles as well

**Comment by darrenmason** [comment]
@philschatz it matches

**Pull request merged**
