### PR TITLE
Add box to copy enrollment code link from to course settings

### PR DESCRIPTION
**Pull request by nathanstitt**
Requires BE PR: https://github.com/openstax/tutor-server/pull/1099

screen shot 2016-05-27 at 5 05 10 pm

### CODE REVIEW

**Comment by jpslav** [comment]
Oh lord.  "strip-hole"?  I just got "broken-instruction".  I think it is time to switch to numeric codes :-)

**Comment by jpslav** [comment]
@nathanstitt can you include in this PR the change from `teacher_join_url` to `teach_url`?

**Comment by philschatz** [comment]
ooh, can't wait to test on dev! Do I need to do anything special or just deploy to dev?

**Comment by nathanstitt** [comment]
@jpslav I could but this only is for the student join URL.  Unless I'm mistaken there's no UI for the teacher join URL, it's only delivered via email.  @openstax/ux can you confirm?

**Comment by jpslav** [comment]
You're right no teacher join URL in UI.  For some reason I always think
there is...

**Comment by philschatz** [comment]
FWIW I keep thinking there is one in there too : (

**Pull request merged**
