### PR TITLE
Dashboard styles

### PR DESCRIPTION
**Pull request by Fredasaurus**
Made some typographic and positioning changes. Also added new book covers.

screen shot 2015-08-05 at 5 20 17 pm

Can we make the bars span 100% here?

screen shot 2015-08-05 at 5 20 17 pm copy

### CODE REVIEW

**Comment by nathanstitt** [comment]
Looks nice.  The fix for 100% width bars is in #592.  That also changes the color key to use flexbox so it aligns vertically.  It'll probably conflict with some of your styles but we can stitch it together without too much trouble.

**Comment by Fredasaurus** [comment]
thanks. Ah cool. that's a lot better than the kludgey height: 30px I put in there.

**Comment by nathanstitt** [comment]
@Fredasaurus #592 was just merged and now this PR has a merge conflict.  Want me to fix it up?

**Comment by Fredasaurus** [comment]
yeah.

**Pull request merged**
