### PR TITLE
Changing link color

### PR DESCRIPTION
**Pull request by Fredasaurus**
Smallest PR ever! Making the link color easier to read.

screen shot 2015-08-18 at 1 24 46 pm

### CODE REVIEW

**Comment by pandafulmanda** [comment]
:+1:

**Comment by Fredasaurus** [comment]
Just changed it, sorry.

**Comment by Fredasaurus** [comment]
screen shot 2015-08-18 at 1 39 39 pm

**Comment by Fredasaurus** [comment]
Liked the other blue better, but it clashed with some other tutor-blues. This is a slight darker version of tutor-info.

**Pull request merged**
