### PR TITLE
add keyboard shortcuts

### PR DESCRIPTION
**Pull request by philschatz**
hello.when answering multiple choice questions use the keys “a”-“d” to select an answer.

TODO:

- [x] only add the key listeners when answering a multiple choice question, not when reviewing an already answered 
- [ ] disable for review when more than one incomplete exercise
- [ ] add enter key handling (maybe by focusing the continue button)
- [ ] add left/right navigation for the reference book
- [ ] add tests

### CODE REVIEW

**Comment by jivewise** [comment]
I feel like 1, 2, 3, 4 would be easier to type...

**Comment by philschatz** [comment]
ah, good point. thoughts @Fredasaurus or @pandafulmanda ?

**Comment by pandafulmanda** [comment]
Hmm...that's a good point...I wonder if there would confusion around 1, 2, 3, 4 mapping to a, b, c, d though.  I feel like @Fredasaurus would have a stronger take on this but I could see it working either way.

**Comment by nathanstitt** [comment]
Yeah, I'd say either one would work.  I also suppose we could support both mappings

**Comment by Fredasaurus** [comment]
That's a tricky one. I think Nathan mat have the best answer. Do we ever have answers that are labeled 1, 2, 3, 4? If so, would we map a, b, c, d to that?

**Comment by philschatz** [comment]
I think multiple choice options are always lettered.

**Comment by pandafulmanda** [comment]
guess this will get ported to openstax/react-components ?

**Comment by philschatz** [comment]
closed in favor of openstax/react-components#16

**Pull request closed without merging**
