### PR TITLE
WIP initial draft of teacher performance book

### PR DESCRIPTION
**Pull request by jpslav**
Welcome to JP's learning experience.  This PR adds a basic version of the teacher's view of the performance book.  I pretty much copied and pasted work from the rest of the frontend team, so cheers to y'all ;-).  

I winged it on the div classes (not knowing the rules there), didn't add any styling, and definitely didn't add tests.  

But it does print the table from the mock API data, so I'm declaring a partial victory :-)

screen shot 2015-04-22 at 10 25 51 pm

### CODE REVIEW

**Comment by pandafulmanda** [comment]
:+1: :smiley_cat:

**Comment by philschatz** [comment]
:sparkles: :heart: I'm Lovin It! <sup>:tm:</sup> :heart: :sparkles:

**Comment by jpslav** [comment]
hahahahah @philschatz  ;-)

**Comment by jpslav** [comment]
thanks @darrenmason, I borrowed **heavily** from your early draft of the learning guide!

**Pull request merged**
