### PR TITLE
move user/tasks to be course specific

### PR DESCRIPTION
**Pull request by philschatz**
@jpslav : Once this is merged BE can remove the route too!

### CODE REVIEW

**Comment by jpslav** [comment]
Thanks @philschatz -- the sooner the better, because our PR that removes this route needs to go in ASAP.

**Comment by pandafulmanda** [comment]
:+1:

**Comment by jpslav** [comment]
thanks @pandafulmanda! @Dantemss you can merge https://github.com/openstax/tutor-server/pull/145 after this PR is merged.

**Comment by jivewise** [comment]
+1

**Pull request merged**
