### PR TITLE
Add time to due at date

### PR DESCRIPTION
**Pull request by nathanstitt**
screen shot 2015-07-23 at 7 52 05 pm

### CODE REVIEW

**Comment by pandafulmanda** [comment]
I think @Fredasaurus is going to not like that hehehehe

**Comment by nathanstitt** [comment]
Yeah, the card I was assigned explicitly said to put the time beside the date.  Otherwise I think we could put something like "All assignments are due by 7pm CST" at the bottom of the panel.

**Comment by philschatz** [comment]
I think this is good for now; @Fredasaurus can suggest otherwise.

**Comment by Fredasaurus** [comment]
If all time at 7:00 it does not need to be repeated. And yeah it look awful.

**Comment by jason-holmes** [comment]
Something more like this would be better.  http://mockups.openstax.org/Tutor_MVP_beta_release/start.html#p=johnny_tran_dashboard_-_visual_design_-_1 <http://mockups.openstax.org/Tutor_MVP_beta_release/start.html#p=johnny_tran_dashboard_-_visual_design_-_1>



-------
Jason Holmes, Ph.D.
User Experience Manager
OpenStax | OpenStax.org
(713) 893-1326

**Pull request merged**
