### PR TITLE
BE stats update

### PR DESCRIPTION
**Pull request by Dantemss**
@darrenmason I'm doing this since the latest change breaks all the code... I did the boring greping part but someone should test this... And make sure those divisions don't blow up (this only covers the old code, I believe?).

2 tests failed but they seem... unrelated? Also, the Gulpfile has a lint problem.

refs openstax/tutor-server#969

### CODE REVIEW

**Comment by Dantemss** [comment]
https://github.com/openstax/tutor-server/pull/969

**Comment by philschatz** [comment]
Is there a corresponding BE PR for this? (is it merged?)

**Comment by Dantemss** [comment]
Ignore this PR for now...

**Comment by Dantemss** [comment]
I'm closing. Reopen if we decide we need this info in other tabs.

**Comment by philschatz** [comment]
huh? So, what is the solution for FE getting the averages in student scores?

**Comment by Dantemss** [comment]
https://github.com/openstax/tutor-server/pull/978

**Pull request closed without merging**
