### PR TITLE
format math in highlight annotations

### PR DESCRIPTION
**Pull request by TomWoodward**
the annotation logic is just ripping out all the mathjax stuff so that it is just the `<math>` element that the document starts with, if there is a mathjaxy way to revert the content on the cloned dom and no affect the actual page that would be ideal, but i couldn't find anything like that.

### CODE REVIEW

**Comment by TomWoodward** [comment]
[Change Request: figure out a solution for highlighting math](https://trello.com/c/AXIaovVM/1502-change-request-figure-out-a-solution-for-highlighting-math)

**Comment by nathanstitt** [comment]
Looks good to me, but waiting to merge until others get a chance to evaluate it on dev server.

**Comment by nathanstitt** [comment]
[T3.highlighting.17 - Prevent highlight from starting mid-word and/or ending mid-word](https://trello.com/c/k5lq2sb9/1564-t3highlighting17-prevent-highlight-from-starting-mid-word-and-or-ending-mid-word)

**Comment by nathanstitt** [comment]
[T3.highlighting.17 - Prevent highlight from starting mid-word and/or ending mid-word](https://trello.com/c/k5lq2sb9/1564-t3highlighting17-prevent-highlight-from-starting-mid-word-and-or-ending-mid-word)

**Pull request merged**
