### PR TITLE
Calendar auto expand

### PR DESCRIPTION
**Pull request by jivewise**
- [x] Update date-picker to auto-expand when focused
- [x] Fix for safari browsers when coming from calendar
- [x] Updated plans to use a read-only date-picker instead of a label

### CODE REVIEW

**Comment by gregfitch** [comment]
:thumbsup: Thanks for the quick turnaround, Jing.

**Comment by philschatz** [comment]
Clicking a second time on the calendar (when it already has focus) does not reopen the calendar. Could the `<input>` be disabled so it never actually gets focus? Also, what happens when the user enters an invalid date?

**Comment by jivewise** [comment]
Now clicking on the input should open up the date picker again.  I also added some initial handling for when an invalid date is entered in the input.

**Comment by philschatz** [comment]
D'oh. It seems this causes a 422 when publishing (see #324) . Will try to merge after walking through the demo script

**Pull request merged**
