### PR TITLE
update book colors for sociology and us history

### PR DESCRIPTION
**Pull request by nathanstitt**

### CODE REVIEW

**Comment by lwtchu** [comment]
:eyes: sorry to barge in. but to better match rex/the cover should we  do white text on navy bg?

**Review by jivey — APPROVED** [review]

**Comment by nathanstitt** [comment]
Heya @lwtchu - I'm going off of https://github.com/openstax/tutor/issues/1715#issuecomment-880020368 for the colors.   Should I update it to have white text?  Sorry for not including a screenshot on this, but it currently looks like:

**Comment by lwtchu** [comment]
@nathanstitt i think for text it's been historically either white or black just to reduce the amount of colors to worry about for contrast with highlighting. I'm looking thru the title cards on tutor for the other books and it seems to be the case :eyes:

**Comment by nathanstitt** [comment]
yep, you're correct, I was mistaken and thought that we'd styled the text using the book colors but looking through other books I see that the text is either white or black. I'll update this to be white.  Thanks @lwtchu !

this is what it'll look like with that change:
image


image

**Comment by lwtchu** [comment]
thank you ~ ~ ~

**Pull request merged**
