### PR TITLE
course listing - book covers / info layout

### PR DESCRIPTION
**Pull request by darrenmason**
image

- [x] updated layout
- [x] updated styling
- [x] book images by course
- [ ] institution name
- [ ] course code
- [ ] instructors

### CODE REVIEW

**Comment by philschatz** [comment]
@jpslav there are a couple missing fields (like "Institution"). Any idea on when those could get added?

**Comment by philschatz** [comment]
Decision was to just skip the institution and image for now since not many people will see it.

**Comment by philschatz** [comment]
closing this for now unless @jason-holmes or @Fredasaurus or @gregfitch think otherwise

**Comment by Fredasaurus** [comment]
We'll need to make some changes, not urgent.

**Pull request closed without merging**
