### PR TITLE
Correct bar lengths on performance forecast, collapse order on dashboard

### PR DESCRIPTION
**Pull request by nathanstitt**
Medium (tablet) size performance forecast:
screen shot 2015-08-05 at 4 11 56 pm

Student dashboard:
screen shot 2015-08-05 at 4 03 54 pm

### CODE REVIEW

**Comment by Fredasaurus** [comment]
looks like the key was moved.

**Comment by nathanstitt** [comment]
Thanks @Fredasaurus.  yep, that'll need a `clear` rule also now. :)

**Comment by nathanstitt** [comment]
screen shot 2015-08-05 at 2 26 15 pm
screen shot 2015-08-05 at 2 26 34 pm

**Comment by kathi-fletcher** [comment]
I like the top mock better for sure.

**Comment by Fredasaurus** [comment]
Can we make the outside padding consistent everywhere?

**Comment by Fredasaurus** [comment]
screen shot 2015-08-05 at 2 31 45 pm

**Comment by Fredasaurus** [comment]
fwiw I have all sides at 30px.

**Comment by nathanstitt** [comment]
@Fredasaurus Gotcha!  Will do.  Here's how it looks at with chapters at 50% 
screen shot 2015-08-05 at 2 32 26 pm

**Comment by Fredasaurus** [comment]
I'm ok with that. That will be a rare case.

**Pull request merged**
