### PR TITLE
performance forecast

### PR DESCRIPTION
**Pull request by darrenmason**
Teacher:
screen shot 2015-08-03 at 8 27 30 am

Student:
screen shot 2015-08-03 at 7 55 46 am

Teacher viewing student:
screen shot 2015-08-03 at 7 57 59 am

- [X] updated teacher/student header
- [x] header info icon / hover
- [x] period tab buttons
- [x] single column weaker areas
- [x] single column chapter/section listing 
- [x] update all titles to 'performance forecast'

### CODE REVIEW

**Comment by darrenmason** [comment]
image

**Comment by darrenmason** [comment]
image

**Comment by philschatz** [comment]
The last commit causes Travis to cry ; (

**Comment by darrenmason** [comment]
image

**Comment by nathanstitt** [comment]
Responsive sizes:
screen shot 2015-08-02 at 9 07 21 pm
screen shot 2015-08-02 at 9 07 47 pm
screen shot 2015-08-02 at 9 08 01 pm

**Comment by Fredasaurus** [comment]
Looking good. One comment: Can we make sure that that chapter overall bar is always greater or equal to the length of the individual bars? That way it always looks superior.

The last one is exactly what I was going to do for an iPad mockup, so thanks for taking care of that work for me.

**Comment by philschatz** [comment]
It seems "My Weaker Areas" can be blank:

image

but otherwise it looks/works Great!

**Comment by nathanstitt** [comment]
@philschatz I think you're viewing outdated code.  The red arrow has been removed from the weaker section.  With that said, it's still a bug because the weaker shouldn't have been empty in that shot because there was a chapter with data present.

It did prompt me to go through and examine the "no data" use case and remove the weakest section from displaying and made few styles changes.

The no-data case now looks like:

Teacher:
screen shot 2015-08-03 at 12 02 41 pm

Student:
screen shot 2015-08-03 at 12 03 17 pm

**Comment by nathanstitt** [comment]
@Fredasaurus I've changed the chapter bar to be a bit taller and wider than the others.  I also changed the border to appear below the bar when it's collapsed to visually separate the chapter's and sections.

screen shot 2015-08-03 at 12 12 13 pm

**Comment by philschatz** [comment]
Cool, thanks!

**Pull request merged**
