### PR TITLE
Selenium: modal is considered closed too early in chrome. 

### PR DESCRIPTION
**Pull request by pandafulmanda**
need to wait until the modal is not present at all.  For use in `openstax/test-automation`

Tests have been fixed/updated as much as possible.  Current failures in this branch from running tests will be due to:
* Teacher task review being unable to render
  * will be fixed when #1046 is merged
* assignment open/due date bugs
  * will be fixed when #1067 is merged
* assignment feedback immediate bug
  * will be fixed when #1069 is merged

### CODE REVIEW

**Comment by philschatz** [comment]
I get the following consistently:
```
[59s] START: Waiting for {"css":".course-scores-wrap"} to show
[59s] END  : Waiting for {"css":".course-scores-wrap"} to show returning=true
[9s] START: Wait and click {"css":".student-name"}
[59s] - START: Looking for {"css":".student-name"}
[59s] - END  : Looking for {"css":".student-name"} returning=function (driver, id) {
  webdriver.Serializable.call(this);

  /** @private {!webdriver.WebDriver} */
  this.driver_ = driver;

  /** @private {!webdriver.promise.Promise.<webdriver.WebElement.Id>} */
  this.id_ = id instanceof webdriver.promise.Promise ?
      id : webdriver.promise.fulfilled(id);
}
[59s] - Found {"css":".student-name"}
[59s] - START: Waiting for {"css":".student-name"} to show
[59s] - END  : Waiting for {"css":".student-name"} to show returning=true
[9s] - Scrolling to el
[9s] - START: Wait until scrolling completes
[9s] - END  : Wait until scrolling completes returning=true
[9s] - Clicking {"css":".student-name"}
--------------------- 8< Snipped >8 ---------------------
  1) Calendar and Stats Clicks an item in the Student Scores (readonly) for BIOLOGY:
     UnknownError: unknown error: Element is not clickable at point (110, 272). Other element would receive the click: <div class="tutor-dialog modal fade in" tabindex="-1" role="dialog" style="display:block;" data-reactid=".t.1">...</div>
  (Session info: chrome=44.0.2403.125)
  (Driver info: chromedriver=2.19.346063 (38b35413bd4a486d436a9749e090454bc9ff6708),platform=Mac OS X 10.9.5 x86_64)
      at Array.forEach (native)
  From: Task: Calendar and Stats Clicks an item in the Student Scores (readonly) for BIOLOGY
      at Array.forEach (native)
```

**Comment by pandafulmanda** [comment]
ah okay, i think i know what's going on, will investigate

**Comment by philschatz** [comment]
Any updates on the investigation?

**Comment by pandafulmanda** [comment]
hmmm...i dont get this error at all, i will keep looking into it...does this still happen for you/which server?

**Comment by pandafulmanda** [comment]
Fixes small scores UI flash bug uncovered by test breaking, fixes the tests as well, making sure that scores table actually is loaded for the period before trying to click on scores table elements

**Comment by philschatz** [comment]
This consistently generates a selenium error for me on `-dev`:

```
[59s] START: Waiting for {"css":".course-scores-container"} to show
[59s] END  : Waiting for {"css":".course-scores-container"} to show returning=true

  1) Calendar and Stats Clicks an item in the Student Scores (readonly) for PHYSICS:
     StaleElementReferenceError: stale element reference: element is not attached to the page document
  (Session info: chrome=44.0.2403.125)
  (Driver info: chromedriver=2.19.346063 (38b35413bd4a486d436a9749e090454bc9ff6708),platform=Mac OS X 10.9.5 x86_64)

```

This error doesn't happen with `master`

**Comment by philschatz** [comment]
Hmm, this now seems to error earlier:

```
  Assignment Publishing Tests
    1) "before each" hook

  7 passing (1m)
  1 failing

  1) Assignment Publishing Tests "before each" hook:
     TypeError: Cannot read property 'appearance' of undefined
      at TestItemHelper.COMMON_ELEMENTS.courseByAppearance (test-integration/helpers/ui/course-select.coffee:15:23)
      at Context.<anonymous> (test-integration/helpers/ui/test-element.coffee:65:30)
      at Utils.verboseWrap (test-integration/helpers/utils/verbose.coffee:120:18)
      at TestItemHelper._this.(anonymous function) [as locator] (test-integration/helpers/ui/test-element.coffee:64:39)
      at TestItemHelper.getLocator (test-integration/helpers/ui/test-element.coffee:88:66)
      at TestItemHelper.getLocator (test-integration/helpers/ui/test-element.coffee:3:59)
      at TestItemHelper.findElement (test-integration/helpers/ui/test-element.coffee:175:33)
      at Object.<anonymous> (test-integration/helpers/ui/test-element.coffee:3:59)
      at CourseSelect.getByType (test-integration/helpers/ui/course-select.coffee:83:49)
      at CourseSelect.goToByType (test-integration/helpers/ui/course-select.coffee:102:21)
      at Context.<anonymous> (test-integration/task-plan/homework.coffee:19:38)
      at Array.forEach (native)
```

**Comment by pandafulmanda** [comment]
Tests have been fixed/updated as much as possible.  Current failures in this branch from running tests will be due to:
* Teacher task review being unable to render

**Comment by philschatz** [comment]
any idea why `-latest` is causing that error("Teacher task review being unable to render")? I noticed it when running the selenium tests

**Comment by pandafulmanda** [comment]
Because the BE's data structure for that has changed, but FE's #1046 hasnt been merged

**Comment by philschatz** [comment]
ah, thanks!

**Pull request merged**
