### PR TITLE
Refactor how selenium TestElement elements are called

### PR DESCRIPTION
**Pull request by philschatz**
Changes the syntax to `courseSelect.el.courseByType('physics').click()` instead of `courseSelect.el.courseByType.click('physics')`

Keeps a deprecation warning in _just in case_.

Thoughts @openstax/tutor-fe @openstax/test ? refs #931

# This PR is not to master. refs #981

### CODE REVIEW

**Comment by pandafulmanda** [comment]
Hey @philschatz looking at this more closely and I realized with this change, to know how to get at the `el`, we have to know how we set the original `locator` and that there are currently two ways to get an `el` and perform actions upon it:

### For some locator setting like this:
```coffee
SCORES_ELEMENTS =
  averageLabel:
    css: '.average-label span:last-child'
  assignmentByType: (type) ->
    css: "a.scores-cell[data-assignment-type='#{type}']"
```

### We have both
```coffee
scoresHelper.el.averageLabel.doSomething()
```
and
```coffee
scoresHelper.el.assignmentByType('reading').doSomething()
```

I think this adds extra overhead in having to think about how we need to get at the `el`.  I think we should go ahead and make the like this:

```coffee
scoresHelper.el.averageLabel().doSomething()
```
as well, so that we always call a function to access our `el`s.  What do you guys think @openstax/tutor-fe ?

**Comment by philschatz** [comment]
I personally like thinking of `averageLabel` as an element-ish thing (the name helps clarify that no additional args are required), but it would be easy to support both (ie empty args returns `@`). So the syntax would be:

- `scoresHelper.el.averageLabel.doSomething()`
- `scoresHelper.el.averageLabel().doSomething()`

**Comment by pandafulmanda** [comment]
The `css:` is optional right now as utils' `toLocator` is being called on it.  `toLocator` gives a warning though, and that's why I was explicit everywhere.  I think the clarity is nice, but it does seem repetitive.

As for supporting both syntaxes, I think that will just lead to confusion, especially when we deprecate the `scoresHelper.el.assignmentByType.doSomething('reading')` syntax.  I think knowing that you'd always access things on `el` one way makes it more clear than any naming we can do.

**Comment by philschatz** [comment]
I guess I think of things under `.el.` as _mostly_ an element that can be clicked/checked-for-existence/etc and only occasionally do they need a _little extra help_ which is when you would add the `('reading')`.

In the (rare?) cases when they take an additional arg I think the 2 options discussed above are:

- name the element describing what the required additional arg is (`el.assignmentByType(t)`)
- have the user read the code to see if the additional arg is optional or not (`el.assignment(t)`)

I guess I'm more likely to type (without looking up the source code):

- `scores.el.title.getText()` than `scores.el.title().getText()`
- `scores.el.assignmentByType('reading').getText()` than `scores.el.assignmentByType.getText('reading')`

What do folks think?

**Comment by jivewise** [comment]
I don't have strong opinions one way or the other, but I do agree it's not a bad thing to make the user read the code to see whether the argument is necessary.

**Comment by jivewise** [comment]
Maybe if there's a function that requires an argument, maybe it should be a verb?  Something like
```el.getAssignmentByType(t)```

**Comment by nathanstitt** [comment]
I think @pandafulmanda's point is a good one.  It does seem confusing to access items that are hung off of `.el` as both a function or a property.  

However, unless we're going to write documentation for all the helpers, then they'll require reading the source to figure out the names anyway.  And if we are writing documentation (which isn't a bad idea), then it doesn't really matter because the differences will be noted there.

**Comment by gregfitch** [comment]
-- DocText --

**Comment by philschatz** [comment]
@gregfitch I think doctext addresses the "how do we write documentation?", but does not address "what should the code convention be?"

**Comment by darrenmason** [comment]
I agree with @jivewise that if an argument is required, we should use verb names.

**Comment by philschatz** [comment]
To maybe help with looking at the options, here is a script with all the `el` entries so far:

```coffee
Calendar.CalendarHelper::el.forecastLink.click()
Calendar.CalendarHelper::el.studentScoresLink.click()
Calendar.CalendarHelper::el.addToggle.click()
Calendar.CalendarHelper::el.addReadingButton.click()
Calendar.CalendarHelper::el.addHomeworkButton.click()
Calendar.CalendarHelper::el.addExternalButton.click()
Calendar.CalendarHelper::el.publishedPlan.click()
Calendar.CalendarHelper::el.draftPlan.click()
Calendar.CalendarHelper::el.openPlan.click()
Calendar.CalendarHelper::el.unopenPlan.click()
Calendar.CalendarHelper::el.planByTitle.click()
Calendar.CalendarHelper::el.publishedPlanByTitle.click()
Calendar.CalendarHelper::el.loadingState.click()
Calendar.CalendarHelper::el.planPopup.click()
Calendar.CalendarHelper.PlanPopupHelper::el.closeButton.click()
Calendar.CalendarHelper.PlanPopupHelper::el.editLink.click()
Calendar.CalendarHelper.PlanPopupHelper::el.reviewLink.click()
Calendar.CalendarHelper.PlanPopupHelper::el.modal.click()
Calendar.CalendarHelper.PlanPopupHelper::el.loadingState.click()
Calendar.CalendarHelper.PlanPopupHelper::el.periodReviewTab.click()
ReadingBuilder::el.name.click()
ReadingBuilder::el.datepickerContainer.click()
ReadingBuilder::el.dateInput.click()
ReadingBuilder::el.datepickerDay.click()
ReadingBuilder::el.readingPlan.click()
ReadingBuilder::el.homeworkPlan.click()
ReadingBuilder::el.externalPlan.click()
ReadingBuilder::el.selectReadingsButton.click()
ReadingBuilder::el.addReadingsButton.click()
ReadingBuilder::el.disabledAddReadingsButton.click()
ReadingBuilder::el.deleteButton.click()
ReadingBuilder::el.saveButton.click()
ReadingBuilder::el.publishButton.click()
ReadingBuilder::el.pendingPublishButton.click()
ReadingBuilder::el.cancelButton.click()
ReadingBuilder::el.hasErrorWarning.click()
ReadingBuilder::el.requiredHint.click()
ReadingBuilder::el.requiredItemNotice.click()
ReadingBuilder::el.anyPlan.click()
ReadingBuilder::el.loadingState.click()
ReadingBuilder::el.selectReadingsList.click()
ReadingBuilder::el.unsavedDialog.click()
CourseSelect::el.courseLink.click()
CourseSelect::el.loadingState.click()
CCDashboard::el.dashboard.click()
CCDashboard::el.inactiveTab.click()
CCDashboard::el.activeTab.click()
CCDashboard::el.viewScoresButton.click()
CCDashboard::el.helpLink.click()
CCDashboard::el.scoresReport.click()
CCDashboard::el.loadingState.click()
StudentDashboard.Dashboard::el.progressGuide.click()
StudentDashboard.Dashboard::el.thisWeek.click()
StudentDashboard.Dashboard::el.visibleEvents.click()
StudentDashboard.Dashboard::el.workableTask.click()
StudentDashboard.Dashboard::el.loadingState.click()
Task.TaskHelper::el.continueButton.click()
Task.TaskHelper::el.enabledContinueButton.click()
Task.TaskHelper::el.disabledContinueButton.click()
Task.TaskHelper::el.stepCrumbs.click()
Task.TaskHelper::el.currentBreadcrumbStep.click()
Task.TaskHelper::el.loadingState.click()
User::el.loginLink.click()
User::el.smallScreenNavbarToggle.click()
User::el.searchQuery.click()
User::el.usernameLink.click()
User::el.usernameInput.click()
User::el.passworkInput.click()
User::el.loginSubmit.click()
User::el.modalClose.click()
User::el.userMenu.click()
User::el.openHamburgerMenu.click()
User::el.logoutForm.click()
User::el.homeLink.click()
User::el.pageTitle.click()
User::el.courseListing.click()
User::el.eitherSignInElement.click()
User::el.loadingState.click()
ReferenceBook.ReferenceBookHelper::el.nextPageButton.click()
ReferenceBook.ReferenceBookHelper::el.tocToggle.click()
ReferenceBook.ReferenceBookHelper::el.exerciseElements.click()
ReferenceBook.ReferenceBookHelper::el.missingExercises.click()
ReferenceBook.ReferenceBookHelper::el.loadingExercises.click()
ReferenceBook.ReferenceBookHelper::el.loadingState.click()
Scores.ScoresHelper::el.ccScoresLink.click()
Scores.ScoresHelper::el.nameHeaderSort.click()
Scores.ScoresHelper::el.dataHeaderSort.click()
Scores.ScoresHelper::el.generateExport.click()
Scores.ScoresHelper::el.downloadExport.click()
Scores.ScoresHelper::el.hsNameLink.click()
Scores.ScoresHelper::el.hsReviewLink.click()
Scores.ScoresHelper::el.periodTab.click()
Scores.ScoresHelper::el.displayAs.click()
Scores.ScoresHelper::el.basedOn.click()
Scores.ScoresHelper::el.scoreCell.click()
Scores.ScoresHelper::el.averageLabel.click()
Scores.ScoresHelper::el.assignmentByType.click()
Scores.ScoresHelper::el.loadingState.click()
Scores.ScoresHelper::el.periodReviewTab.click()
```

and source code to generate:

```coffee
_ = require 'underscore'
HELPERS = require './helpers'
TEST = {
  utils:
    verboseWrap: () ->
}

printEls = (name) ->
  h = HELPERS
  for ctx in name.split('.')
    h = h[ctx]

  h = new h(TEST)
  for key in Object.keys(h.el)
    console.log "#{name}::el.#{key}.click()"

  unless h['isDisplayed'] # Skip if it extends TestItemHelper
    for key in Object.keys(h)
      if key isnt 'el'
        console.log "#{name}::#{key}()"


printEls('Calendar.CalendarHelper') #Fixme
printEls('Calendar.CalendarHelper.PlanPopupHelper') #fixme
printEls('ReadingBuilder')
printEls('CourseSelect')
printEls('CCDashboard')
printEls('StudentDashboard.Dashboard') #fixme
# printEls('StudentDashboard.Event') #fixme
printEls('Task.TaskHelper') #fixme
printEls('User')
printEls('ReferenceBook.ReferenceBookHelper') #fixme
printEls('Scores.ScoresHelper') #fixme
```

**Comment by philschatz** [comment]
Oh, what if we enable both ways (that's what this PR did) and try it out for a sprint? I think writing the code might be a better way to exercise the various options. Also, with this code, we would be able to add "Deprecation" warnings once we pick. Thoughts?

**Comment by pandafulmanda** [comment]
the doc generator is cool, i was wondering if we could something like that, or even have something like that be a script people can run on the terminal list what's available

it sounds like we are saying, let's go with `el`s being mostly properties, and then having them be a function that is named with a verb only when needed, as is with this PR

**Pull request merged**
