### PR TITLE
Use the new course role API

### PR DESCRIPTION
**Pull request by Dantemss**
Requires openstax/tutor-server#2402

For courses only (not roster, performance, scores):
- Use student_record instead of students
- Use teacher_record instead of teachers
- Use the new teacher_student_records when using "view as student"

### CODE REVIEW

**Comment by Dantemss** [comment]
There's some issue with assuming a non-default role (view as student)

**Comment by Dantemss** [comment]
Requires https://github.com/openstax/tutor-server/pull/2402

**Comment by Dantemss** [comment]
I think the add-edit-questions E2E might need the new Docker image from the backend before it'll pass.

**Review by jivey — APPROVED** [review]
Looks good and tested well 👍

**Pull request merged**
