### PR TITLE
Update react bootstrap

### PR DESCRIPTION
**Pull request by darrenmason**
This update fixes the popover positioning bug present in ie and firefox, pertaining to:
https://www.pivotaltracker.com/story/show/109985726

Requires that openstax-react-components peerDependencies be updated to 0.23.0

Have been testing and I found no issues due to changes in framework so far.

react-bootstrap changelog of issue:

- [66e41a4](../../commit/66e41a4) [fixed] Fix scroll top calculation for overlays

Refs #922

### CODE REVIEW

**Comment by philschatz** [comment]
Thanks! I'm curious, what issues did you find with 0.24?

**Comment by philschatz** [comment]
travis seems to be complaining about versions of specific packages not working. Can you try and find out which ones? It might be helpful for @pandafulmanda 's list too.

**Comment by darrenmason** [comment]
.24 broke the modals for some reason;  There was no clear console warn/error, but I believe it had to do with changes to overlay trigger / modal format or required proptypes.

**Comment by darrenmason** [comment]
I think travis needs openstax-react-components peerDependencies be updated to 0.23.0

**Comment by pandafulmanda** [comment]
i can update the `peerDependencies` off of the version of `react-components` being used in this branch, or we may have to pull in the commits from #925 with an update to `peerDependencies` off of `react-components@master`

**Comment by pandafulmanda** [comment]
I've updated `openstax-react-components` for this, is this PR waiting on anything else?

**Comment by darrenmason** [comment]
nope, looks good.

**Pull request merged**
